# _config.yml
title: "我的技术博客"
description: "记录学习与开发笔记"
theme: jekyll-theme-minimal

# ✅ 正确配置
url: "https://yuan-2024.github.io/iyouzhang.github.io"  # 仅用户名部分
baseurl: ""  # 保持为空

# 可选添加
author: "yuanzhang"
email: "your@email.com"
